Repository IU-Capstone-Project-2024/Team-44, pull requests merged in 2024-06, with the labels that each got.

#12 Create main.yml
  .github/workflows/main.yml
Labels: deploy

#14 Update README.md
  README.md
Labels: documentation

#21 adding docker
  .github/workflows/main.yml
  docker-compose.yml
  rag_backend/Dockerfile
  rag_backend/rag_backend/settings.py
  rag_backend/requirements.txt
Labels: deploy

#23 Adding Vector Database, Embedding functions
  lang_graph/VectorSpace/Embedder.py
  lang_graph/VectorSpace/VectorDB.py
  lang_graph/notebooks/embedding_vector_database.ipynb
  lang_graph/notebooks/test_txt.txt
  lang_graph/notebooks/testz.ipynb
  lang_graph/notebooks/text spitters.ipynb
  lang_graph/semantic_router_testz.ipynb
Labels: ML

#28 Router update: work with vector store. Need to be tested with backend
  lang_graph/VectorSpace/VectorDB.py
  lang_graph/VectorSpace/__init__.py
  lang_graph/__init__.py
  lang_graph/agents/__init__.py
  lang_graph/router.py
Labels: ML

#29 Last Router Version
  lang_graph/VectorSpace/__init__.py
  lang_graph/agents/QuizGenerator.py
  lang_graph/requirements.txt
  lang_graph/router.py
Labels: backend, ML

#42 Tests & Frontend
  .gitignore
  frontend/package-lock.json
  frontend/temp-name/.gitignore
  frontend/temp-name/.npmrc
  frontend/temp-name/.prettierignore
  frontend/temp-name/.prettierrc
  frontend/temp-name/README.md
  frontend/temp-name/eslint.config.js
  frontend/temp-name/package-lock.json
  frontend/temp-name/package.json
  frontend/temp-name/src/app.d.ts
  frontend/temp-name/src/app.html
  frontend/temp-name/src/data-store.js
  frontend/temp-name/src/lib/index.ts
  frontend/temp-name/src/routes/+layout.svelte
  frontend/temp-name/src/routes/+page.svelte
  frontend/temp-name/src/routes/about/+page.svelte
  frontend/temp-name/src/routes/contacts/+page.svelte
  frontend/temp-name/src/routes/home/+page.svelte
  frontend/temp-name/src/routes/home/LeftBar.svelte
  frontend/temp-name/src/routes/signin/+page.svelte
  frontend/temp-name/src/routes/signout/+page.svelte
  frontend/temp-name/src/routes/signup/+page.svelte
  frontend/temp-name/src/static/Navbar.svelte
  frontend/temp-name/static/favicon.png
  frontend/temp-name/svelte.config.js
  frontend/temp-name/tsconfig.json
  frontend/temp-name/vite.config.ts
  rag_backend/app1/__init__.py
  rag_backend/app1/test.py
  rag_backend/app1/tests.py
  rag_backend/app1/views.py
  rag_backend/authentication/migrations/0004_user_email_verification_token_alter_user_is_active.py
  rag_backend/authentication/models.py
  rag_backend/authentication/tests.py
  rag_backend/authentication/urls.py
  rag_backend/authentication/views.py
  rag_backend/rag_backend/settings.py
  rag_backend/some.py
Labels: backend, frontend

#43 adding ollama to docker-compose
  .github/workflows/main.yml
  docker-compose.yml
  rag_backend/Dockerfile
  rag_backend/authentication/tests.py
  rag_backend/authentication/views.py
  rag_backend/rag_backend/settings.py
  rag_backend/requirements.txt
Labels: deploy
